/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        gray: "#958B8B",
        black: "#000",
        white: "#fff",
        hover: "#DAA37F",
        icedCitrus: "#FFCC81",
        saigon: "#FBF4E9",
        pandan: "#DDE9CF",
        espressoFrappe: "#B1805E",
        caramelFrappe: "#C99E6C",
        mochaFrappe: "#CCA387",
        whiskeySour: "#B67132",
        wildBerryWhiskey: "#CD9240",
        soloEspresso: "#E7BD8B",
        doppioEspresso: "#DEAA6C",
        americano: "#A15F22",
        macchiato: "#F0E5C9",
        piccolo: "#BD8C61",
        flatWhite: "#CDAF8F",
        capu: "#E7D8B5",
        latte: "#EAD2AA",
        mocha: "#E9D4A9",
        whiteLatte: "#D4BCAC",
        whiteMint: "#F2DACA",
        babycino: "#F5F7F6",
        cfTrung: "#9D7C50",
        cfPhinBlack: "#714729",
        cfPhinWhite: "#AE754C",
        cfd: "#5C3920",
        cfsd: "#8A5834",
        bacXiu: "#C7AD7B",
        geisha_gradient_1: "#FF8F8C",
        geisha_gradient_2: "#C13C6C",
        aro_gradient_1: "#DC7F28",
        aro_gradient_2: "#F3E3AA",
        ey_gradient_1: "#EF6651",
        ey_gradient_2: "rgba(247, 187, 54, 0.5) 100%",
        colom_gradient_1: "#A86549",
        colom_gradient_2: "#CD8122",
        ethi_gradient_1: "#FEEAFF",
        ethi_gradient_2: "#FDDFA5",
        su_gradient_1: "#AB1D1D",
        su_gradient_2: "#AD6C2A",
      },
    },
  },
  plugins: [],
};
